apiVersion: v1
kind: Pod
metadata:
      name: worker-app-pod
      labels:
            name: worker-app-pod
            app: demo-voting-app
spec:
      containers:
        - name: working-app
          image: dockersamples/examplevotingapp_worker